### ISSUE TITLE
Install problem on last ubuntu 

### ISSUE THREAD

**Issue by juliendsv** [centurion-project/Centurion#1]
Hi just checkout the project to play a bit with it

I met this problem when executing ./bin/zf.sh check install :

PHP Notice:  Undefined index: OS in /home/jdasilva/workspace_indigo/centurion/library/Centurion/Tool/Project/Provider/Install.php on line 275
PHP Stack trace:
PHP   1. {main}() /home/jdasilva/workspace_indigo/centurion/bin/zf.php:0
PHP   2. ZF::main() /home/jdasilva/workspace_indigo/centurion/bin/zf.php:636
PHP   3. ZF->run() /home/jdasilva/workspace_indigo/centurion/bin/zf.php:74
PHP   4. ZF->_runTool() /home/jdasilva/workspace_indigo/centurion/bin/zf.php:117
PHP   5. Zend_Tool_Framework_Client_Abstract->dispatch() /home/jdasilva/workspace_indigo/centurion/bin/zf.php:612
PHP   6. Zend_Tool_Framework_Client_Abstract->_handleDispatch() /home/jdasilva/workspace_indigo/centurion/library/Zend/Tool/Framework/Client/Abstract.php:241
PHP   7. Zend_Tool_Framework_Client_Abstract->_handleDispatchExecution() /home/jdasilva/workspace_indigo/centurion/library/Zend/Tool/Framework/Client/Abstract.php:318
PHP   8. call_user_func_array() /home/jdasilva/workspace_indigo/centurion/library/Zend/Tool/Framework/Client/Abstract.php:324
PHP   9. Centurion_Tool_Project_Provider_Install->check() /home/jdasilva/workspace_indigo/centurion/library/Zend/Tool/Framework/Client/Abstract.php:0

Notice: Undefined index: OS in /home/jdasilva/workspace_indigo/centurion/library/Centurion/Tool/Project/Provider/Install.php on line 275

Call Stack:
    0.0010     438640   1. {main}() /home/jdasilva/workspace_indigo/centurion/bin/zf.php:0
    0.0010     438640   2. ZF::main() /home/jdasilva/workspace_indigo/centurion/bin/zf.php:636
    0.0035     750824   3. ZF->run() /home/jdasilva/workspace_indigo/centurion/bin/zf.php:74
    0.0036     750824   4. ZF->_runTool() /home/jdasilva/workspace_indigo/centurion/bin/zf.php:117
    0.0044     836868   5. Zend_Tool_Framework_Client_Abstract->dispatch() /home/jdasilva/workspace_indigo/centurion/bin/zf.php:612
    0.1097    6676728   6. Zend_Tool_Framework_Client_Abstract->_handleDispatch() /home/jdasilva/workspace_indigo/centurion/library/Zend/Tool/Framework/Client/Abstract.php:241
    0.1098    6676892   7. Zend_Tool_Framework_Client_Abstract->_handleDispatchExecution() /home/jdasilva/workspace_indigo/centurion/library/Zend/Tool/Framework/Client/Abstract.php:318
    0.1098    6677220   8. call_user_func_array() /home/jdasilva/workspace_indigo/centurion/library/Zend/Tool/Framework/Client/Abstract.php:324
    0.1098    6677412   9. Centurion_Tool_Project_Provider_Install->check() /home/jdasilva/workspace_indigo/centurion/library/Zend/Tool/Framework/Client/Abstract.php:0

Had it fixed by adding this on the line 274 in /library/Centurion/Tool/Project/Provider/Install.php
if (isset($_SERVER['OS']) && preg_match('`Window`i', $_SERVER['OS'])) {

The $_SERVER['OS'] doesn't exist on my machine.

Just to let you know 

Cheers

**Comment by lchenay** [comment]
Thanks for you notification.
It's fixed in next Centurion version.
