### ISSUE TITLE
Invalid controller specified (admin-flatpage-position)

### ISSUE THREAD

**Issue by rdphv** [centurion-project/Centurion#5]
missing file "/application/modules/cms/controllers/AdminFlatpagePositionController.php" in v0.2

**Comment by rdphv** [comment]
Il semble manquer le module "admin flatpage position"

**Comment by lchenay** [comment]
Ce controller n'est plus utile et a été supprimé de la version 0.2
Comment est-tu tombé sur cette erreur ? Reste-t-il un lien dans la navigation ?

**Comment by rdphv** [comment]
Dans l'admin dans le menu Pages j'ai encore le lien Position
