### ISSUE TITLE
What is the default password for admin panelt after installation?

### ISSUE THREAD

**Issue by XBeg9** [centurion-project/Centurion#6]
What is the default password for admin panelt after installation?
Thanks!

**Comment by lchenay** [comment]
The default login/password is: admin/admincenturion

**Comment by centurion-project** [comment]
Hello, 

the login is : admin 
and the password is : admincenturion 

Regards 

Raphael Theet (via mobile)
Octave & Octave
http://www.octaveoctave.com
+33 6 14 67 31 23
