### ISSUE TITLE
Impossible to customize _dateFormat

### ISSUE THREAD

**Issue by aurmil** [centurion-project/Centurion#8]
In a controller which extends Centurion_Controller_CRUD (so Centurion_Controller_AGL too), it is not possible to specify a date format with "protected $_dateFormat = '...';" as in Centurion_Controller_AGL, there is "$this->_dateFormat = ..." in __construct() method
may be this would have to be "if (null === $this->_dateFormat) $this->_dateFormat = ..."

**Comment by aurmil** [comment]
and "protected $_dateFormat = null;" should be declared in Centurion_Controller_AGL, not in Centurion_Controller_CRUD

**Comment by lchenay** [comment]
You're right. 
I will fix this
